# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jim D'Angelo
tagline:          Software Engineer
description:      Random thoughts about building software, running a company, and being a human.
url:              http://dangeloj.github.io
baseurl:          /
hide_ads:         false

author:
  name:           "Jim D'Angelo"
  url:            https://twitter.com/jjvdangelo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dangeloj/dangeloj.github.io
